#!/bin/sh

# Welcome to the laptop script!
# Be prepared to turn your laptop (or desktop, no haters here)
# into an awesome development machine.

_dir="$HOME/.laptop"
_uname="$(uname -s | tr '[:upper:]' '[:lower:]')"

if [ ! -f ".git/config" ] || ! grep -q "advisr-io/laptop.git" ".git/config"; then
  sh -c "$(curl -fsS "https://raw.githubusercontent.com/advisr-io/laptop/main/${_uname}_stage_one")"
  git clone git@github.com:advisr-io/laptop.git "$_dir"
  sh -c "$(curl -fsS "https://raw.githubusercontent.com/advisr-io/laptop/main/${_uname}_stage_two")"
else
  sh -c "./${_uname}_stage_one"
  sh -c "./${_uname}_stage_two"
fi
