#!/bin/sh

# Welcome to the laptop script!
# Be prepared to turn your laptop (or desktop, no haters here)
# into an awesome development machine.

fancy_echo() {
  printf "\n%s\n" "$1";
}

_dir="$HOME/.laptop"
_uname="$(uname -s | tr '[:upper:]' '[:lower:]')_$(uname -m)"

if ! grep -q "advisr-io/laptop.git" ".git/config"; then
  sh -c "$(curl -fsS "https://raw.githubusercontent.com/advisr/laptop/updates/${_uname}_stage_one")"
  git clone git@github.com:advisr-io/laptop.git "$_dir"
  cd "$_dir" || exit
fi

sh -c "./${_uname}_stage_two"
